In [3]:
# Python program to illustrate the concept
# of threading
# importing the threading module
import threading


def print_cube(num):
	# function to print cube of given num
	print("Cube: {}" .format(num * num * num))


def print_square(num):
	# function to print square of given num
	print("Square: {}" .format(num * num))


if __name__ =="__main__":
	# creating thread
	t1 = threading.Thread(target=print_square, args=(10,))
	t2 = threading.Thread(target=print_cube, args=(10,))

	# starting thread 1
	t1.start()
	# starting thread 2
	t2.start()

	# wait until thread 1 is completely executed
	t2.join()
	# wait until thread 2 is completely executed
	t1.join()

	# both threads completely executed
	print("Done!")


Square: 100
Cube: 1000
Done!


In [14]:
import cv2
a=cv2.imread("/home/pradeep/Downloads/phone_inp_2828/phone_inp/video_frames_for_surendra/overlay_white_and_defect.jpg")
counter= 150
for i in range(30):
    cv2.imwrite(f'/home/pradeep/Downloads/frames (1)/frames/Striching_video/{counter:03}.jpg',a)
    counter=counter+1

In [1]:
for i in range(10):
    print(f'{i:03}')

000
001
002
003
004
005
006
007
008
009


In [2]:
count=25
for i in range(10):
    print(f'{count:03}')
    count=count + 1

025
026
027
028
029
030
031
032
033
034


In [13]:
import cv2
a=cv2.imread("/home/pradeep/Downloads/phone_inp_2828/phone_inp/IMG_20220907_162828.jpg")
b=cv2.imread("/home/pradeep/Downloads/phone_inp_2828/phone_inp/output_red_only_defect.jpg")
overlay=cv2.addWeighted(a,0.4,b,0.6,0)
resize=cv2.resize(overlay,(1600,800))
cv2.imwrite("/home/pradeep/Downloads/phone_inp_2828/phone_inp/video_frames_for_surendra/overlay_white_and_defect.jpg",overlay)
cv2.imshow("test",resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
import cv2
import numpy as np
import glob

frameSize = (4000, 3000)

out = cv2.VideoWriter('/home/pradeep/Downloads/frames_(1)/frames/output_video_processing.avi',cv2.VideoWriter_fourcc(*'DIVX'), 12, frameSize)

for filename in glob.glob('/home/pradeep/Downloads/frames_(1)/frames/Striching_video/*.jpg'):
    img = cv2.imread(filename)
    out.write(img)

out.release()

In [18]:
from threading import *


In [23]:
def new():
    for x in range(6):
        print("child Executing")

t1=Thread(target=new)
t1.start()
# t1.join()
print("bye")

child Executing
child Executing
child Executing
child Executing
child Executing
child Executing
bye


In [35]:
import time
def a(num):
    for x in range(6):
        print(x%2)

    for x in range(6):
        print(x%2)

def b(num):
    for x in range(6):
        print(x%3)

num=[6,9,3,1,2]
s=time.time()
a(num)
b(num)
e=time.time()

print(e-s)




0
1
0
1
0
1
0
1
2
0
1
2
8.320808410644531e-05


In [32]:
0.0006525516510009766
0.0016107559204101562

0.0016107559204101562

In [1]:
import time
from multiprocessing import Pool


def square(x):
    print(f"start process:{x}")
    square = x * x
    print(f"square {x}:{square}")
    time.sleep(1)
    print(f"end process:{x}")


if __name__ == "__main__":
    starttime = time.time()
    pool = Pool()
    pool.map(square, range(0, 5))
    pool.close()
    endtime = time.time()
    print(f"Time taken {endtime-starttime} seconds")

start process:1start process:2start process:3start process:0start process:4




square 1:1square 3:9square 4:16square 2:4square 0:0




end process:3end process:2end process:1end process:0


end process:4

Time taken 1.037123203277588 seconds


In [2]:
import multiprocessing

import numpy as np


data_pairs = [ [3,5], [4,3], [7,3], [1,6] ]


def myfunc(p):

    product_of_list = np.prod(p)

    return product_of_list


if __name__ == '__main__':

    pool = multiprocessing.Pool(processes=4)

    result_list = pool.map(myfunc, data_pairs)

    print(result_list)

[15, 12, 21, 6]


In [5]:
import cv2
import os
import glob

filename=glob.glob("/home/pradeep/Downloads/frames_(1)/frames/Striching_video/*.jpg")
for i in filename:
    a=i.split("/")[-1]
    print(a)
    b=cv2.imread(i)
    cv2.imwrite(f'/home/pradeep/Downloads/frames_(1)/frames/Striching_video/test_sample/{a}.jpg',b)

In [12]:
import cv2
import glob
import time

def main(img,a):
    b=cv2.imread(img)
    cv2.imwrite(f'/home/pradeep/Downloads/frames_(1)/frames/Striching_video/test_sample/{a}.jpg',b)

    

if __name__ == '__main__':
    starttime = time.time()
    filename=glob.glob("/home/pradeep/Downloads/frames_(1)/frames/Striching_video/*.jpg")
    for i in filename:
        a=i.split("/")[-1]
        main(i,a)
    endtime = time.time()
    print(f"Time taken {endtime-starttime} seconds")




[0, 1, 4, 9, 16]
Time taken 39.57829570770264 seconds


In [14]:
import multiprocessing
import cv2
import glob
import time

def main(img,a):
    b=cv2.imread(img)
    cv2.imwrite(f'/home/pradeep/Downloads/frames_(1)/frames/Striching_video/test_sample/testsample/{a}.jpg',b)

    # print("hello")


if __name__ == '__main__':
    starttime = time.time()
    pool = multiprocessing.Pool(processes=6)
    list1=[]
    
    filename=glob.glob("/home/pradeep/Downloads/frames_(1)/frames/Striching_video/*.jpg")
    for i in filename:
        a=i.split("/")[-1]
        
        list1.append([i,a])
        
    
    #pool.apply_async(main,args=list1)
    pool.starmap(main,list1)
    endtime = time.time()
    print(f"Time taken {endtime-starttime} seconds")




049116


Time taken 10.14504075050354 seconds




In [5]:
def add(a,b):
    return a+b

res=add(5,2)

print(res)

7


In [21]:
class a:
    def __init__(self) -> None:
        pass

    def add(a,b):
        c=a+b
        return c
class b(a):
    def __init__(self) -> None:
        super().__init__()
    def sub(a,b):
        return a-b
if __name__ == '__main__':
    
    test1=b.sub(3,2)
    test=b.add(2,3)
    print(test1)
    print(test)


1
5


In [8]:
# Python program to illustrate the concept
# of threading
# importing the threading module
import threading
import time
import multiprocessing


def print_cube(num):
	# function to print cube of given num
	print("Cube: {}" .format(num * num * num))


def print_square(num):
	# function to print square of given num
	print("Square: {}" .format(num * num))


if __name__ =="__main__":
	starttime=time.time()

	# creating thread
	t1 = threading.Thread(target=print_square, args=(10,))
	t2 = threading.Thread(target=print_cube, args=(10,))

	pool = multiprocessing.Pool(processes=6)

	# starting thread 1
	t1.start()
	pool.map(print_square,iterable=1)
	# starting thread 2
	t2.start()
	pool.map(print_cube,iterable=1)

	# wait until thread 1 is completely executed
	t1.join()
	# wait until thread 2 is completely executed
	t2.join()

	# both threads completely executed
	print("Done!")
	endtime=time.time()
	print(endtime-starttime)


Square: 100


TypeError: 'int' object is not iterable

In [2]:
import cv2 
import threading
def stream(a):
    key = cv2. waitKey(1)
    webcam = cv2.VideoCapture(a)
    while True:
        try:
            check, frame = webcam.read()
            print(check) #prints true as long as the webcam is running
            print(frame) #prints matrix values of each framecd 
            cv2.imshow("Capturing", frame)
            key = cv2.waitKey(1)
            if key == ord('s'): 
                cv2.imwrite(filename='saved_img.jpg', img=frame)
                webcam.release()
                img_ = cv2.imread('saved_img.jpg', cv2.IMREAD_ANYCOLOR)
                
                print("Resizing image to 28x28 scale...")
                img_ = cv2.resize(img_,(28,28))
                print("Resized...")
                img_resized = cv2.imwrite(filename='saved_img-final.jpg', img=img_)
                print("Image saved!")
            
                break
            elif key == ord('q'):
                print("Turning off camera.")
                webcam.release()
                print("Camera off.")
                print("Program ended.")
                cv2.destroyAllWindows()
                break
            
        except(KeyboardInterrupt):
            print("Turning off camera.")
            webcam.release()
            print("Camera off.")
            print("Program ended.")
            cv2.destroyAllWindows()
            break

def stream1(a):
    key = cv2. waitKey(1)
    webcam = cv2.VideoCapture(a)
    while True:
        try:
            check, frame = webcam.read()
            print(check) #prints true as long as the webcam is running
            print(frame) #prints matrix values of each framecd 
            cv2.imshow("Capturing1", frame)
            key = cv2.waitKey(1)
            if key == ord('s'): 
                cv2.imwrite(filename='saved_img.jpg', img=frame)
                webcam.release()
                img_ = cv2.imread('saved_img.jpg', cv2.IMREAD_ANYCOLOR)
                
                print("Resizing image to 28x28 scale...")
                img_ = cv2.resize(img_,(28,28))
                print("Resized...")
                img_resized = cv2.imwrite(filename='saved_img-final.jpg', img=img_)
                print("Image saved!")
            
                break
            elif key == ord('q'):
                print("Turning off camera.")
                webcam.release()
                print("Camera off.")
                print("Program ended.")
                cv2.destroyAllWindows()
                break
            
        except(KeyboardInterrupt):
            print("Turning off camera.")
            webcam.release()
            print("Camera off.")
            print("Program ended.")
            cv2.destroyAllWindows()
            break

#obj=stream("rtsp://192.168.1.96:5540/ch0")

if __name__ =="__main__":
    # creating thread
    t1 = threading.Thread(target=stream, args=("rtsp://192.168.1.96:5540/ch0",))
    t2 = threading.Thread(target=stream1, args=(0,))
 
    # starting thread 1
    t1.start()
    # starting thread 2
    t2.start()
 

True
[[[ 95  95  95]
  [ 95  95  95]
  [ 95  95  95]
  ...
  [146 144 144]
  [144 144 144]
  [144 144 144]]

 [[ 95  95  95]
  [ 95  95  95]
  [ 95  95  95]
  ...
  [146 144 144]
  [146 144 144]
  [146 144 144]]

 [[ 95  95  95]
  [ 95  95  95]
  [ 97  97  97]
  ...
  [146 144 144]
  [144 144 144]
  [144 144 144]]

 ...

 [[ 39  61  84]
  [ 39  61  84]
  [ 39  59  79]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[ 39  61  84]
  [ 39  61  84]
  [ 39  59  76]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[ 33  56  77]
  [ 34  57  78]
  [ 23  40  57]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
True
[[[ 32  12 139]
  [ 32  12 139]
  [ 32  12 139]
  ...
  [176 172 150]
  [177 173 151]
  [177 173 151]]

 [[ 32  12 139]
  [ 32  12 139]
  [ 32  12 139]
  ...
  [163 159 137]
  [164 160 138]
  [164 160 138]]

 [[ 31  11 138]
  [ 31  11 138]
  [ 31  11 138]
  ...
  [149 145 123]
  [150 146 124]
  [150 146 124]]

 ...

 [[ 60  93 138]
  [ 60  93 138]
  [ 60  93

In [1]:


import threading
import cv2

class Thread (threading.Thread):
    def __init__(self, threadID,ip):
        threading.Thread.__init__(self)
        self.threadID = threadID
        self.ip = ip

    def run(self):
        print("Start threadID" +str(self.threadID))
        Core.detection(self.ip)
        print("Exiting " + str(self.threadID))
class Core:
    @staticmethod
    def detection(ip):
        capture = cv2.VideoCapture(ip)
        capture.set(cv2.CAP_PROP_BUFFERSIZE, 0)
        while (capture.isOpened()):

            ret, frame = capture.read()
            if ret:
                frame = cv2.resize(frame,(600,400))
                cv2.imshow(ip,frame)
                #cv2.waitKey(1)
                if cv2.waitKey(1) & 0xFF == ord('q'):
                    break
            else:
                print('attempting to reconnect', ip)
                # threads = []
                # for i, cam in enumerate(ip):
                #     thread1 = Thread(i, cam)
                #     threads.append(thread1)
                # for i in threads:
                #     i.start()
                # thread1 = Thread(1, ip)
                # thread1.start()
                Core.detection(ip)
        capture.release()
        cv2.destroyAllWindows()
if __name__=='__main__':
    cam_list=[
           "rtsp://192.168.1.96:5540/ch0","rtsp://192.168.1.110:5540/ch0"
            ]
    threads = []
    for i, cam in enumerate(cam_list):
        thread1 = Thread(i, cam)
        threads.append(thread1)
    for i in threads:
        i.start()



Start threadID0Start threadID1



: 

In [1]:
import concurrent.futures
import cv2

RTSP_List = [("rtsp://192.168.1.96:5540/ch0",0), ("rtsp://192.168.1.110:5540/ch0",1)]


def url_to_video(tup):
    url,index = tup
    video = cv2.VideoCapture(url)
    while True:
        _, frame = video.read()
        cv2.imshow(f"RTSP {index}", frame)
        cv2.moveWindow(f"RTSP {index}", index*300, 0)
        k = cv2.waitKey(1)
        if k == ord('q'):
            break
    video.release()


while True:
    with concurrent.futures.ThreadPoolExecutor() as executor:
        executor.map(url_to_video, RTSP_List)
    cv2.destroyAllWindows()

: 

: 

In [1]:
from flask import Flask, Response
import cv2
app = Flask(__name__)
video = cv2.VideoCapture("rtsp://192.168.1.96:5540/ch0")
@app.route('/')
def index():
    return "Default Message"
def gen(video):
    while True:
        success, image = video.read()
        ret, jpeg = cv2.imencode('.jpg', image)
        frame = jpeg.tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')@app.route('/video_feed')
def video_feed():
    global video
    return Response(gen(video),
                    mimetype='multipart/x-mixed-replace; boundary=frame')
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=2204, threaded=True)

 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:2204
 * Running on http://192.168.1.148:2204
Press CTRL+C to quit
192.168.1.148 - - [11/Nov/2022 12:32:40] "GET / HTTP/1.1" 200 -
192.168.1.148 - - [11/Nov/2022 12:32:41] "GET / HTTP/1.1" 200 -
192.168.1.148 - - [11/Nov/2022 12:32:41] "GET / HTTP/1.1" 200 -
192.168.1.148 - - [11/Nov/2022 12:32:58] "GET / HTTP/1.1" 200 -


In [26]:
def func1():
    print("hii")
    def func2():
        print("hello")

func1()

hii


In [28]:
def func1(func):
    a="string"
    
    def func2():
        print("string Hello")
        func()
    return func2


@func1
def func3():
    print("hello")

func3()

string Hello
hello


In [27]:
from datetime import datetime


def log_datetime(func):
    '''Log the date and time of a function'''

    def wrapper():
        print(f'Function: {func.__name__}\nRun on: {datetime.today().strftime("%Y-%m-%d %H:%M:%S")}')
        print(f'{"-"*30}')
        func()
    return wrapper


@log_datetime
def daily_backup():

    print('Daily backup job has finished.')   

     
daily_backup()



Function: daily_backup
Run on: 2022-11-11 17:12:18
------------------------------
Daily backup job has finished.


In [5]:
import cv2
class A:
    def hello():
        a="string"
        return "hello"


class B:
    def Hii():
        return "hii"

obj=A.hello()
print(obj.a)

AttributeError: 'function' object has no attribute 'a'